### ISSUE TITLE
rlwrap: error: My terminal reports width=0 (is it emacs?) 

### ISSUE THREAD

**Issue by kforner** [Raku/docker#3] opened 2015-12-07 12:56 UTC
on ubuntu 14.04, with gnome-terminal and bash:

> docker run -ti rakudo-star
> rlwrap: error: My terminal reports width=0 (is it emacs?)  I can't handle this, sorry!

**Comment by bhtek** [comment] 2016-04-08 01:39
I am having the same issue on Ubuntu as well as OpenSUSE.

**Comment by hoelzro** [comment] 2016-04-08 19:59
@bhtek Which versions of Ubuntu/OpenSUSE?  Are you also using gnome-terminal and bash?

@kforner @bhtek Which version of docker are you using?

**Comment by kforner** [comment] 2016-04-11 09:43
```
> docker version 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by hoelzro** [comment] 2016-04-12 03:56
@kforner I tried spinning up an Ubuntu VM to test this out, but installing docker via apt gives me Docker 1.6.2.  Did you build docker yourself, or is there a more up-to-date package I should try?

**Comment by kforner** [comment] 2016-04-12 06:41
Which Ubuntu version ? Have you updated the package list ? The crurent
version is 1.10 i think

**Comment by moritz** [comment] 2016-04-12 06:55
@hoelzro https://docs.docker.com/engine/installation/linux/ubuntulinux/ has instructions for adding a package source which is more up-to-date.

**Comment by hoelzro** [comment] 2016-04-12 12:41
@kforner The current version is something like 1.10, but that's what I have on my machine (Arch), so I want to try to be as precise as possible to try and duplicate this.
@moritz Thanks for the link; I'll try that out!

**Comment by hoelzro** [comment] 2016-04-12 17:57
@kforner Alright; I've updated docker according to @moritz' instructions; this is what I have on my Ubuntu VM:

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

This is on 14.04 and this setup works for me; would you mind upgrading to docker 1.10 to see if that resolves your issue?

**Comment by hoelzro** [comment] 2016-04-27 00:02
@kforner Have you tried docker 1.10 to see if that fixes the problem?

**Comment by kforner** [comment] 2016-04-27 07:49
Hi. No I can't. The 1.10 version is not compatible with my docker registry.

**Comment by washort** [comment] 2016-05-03 16:06
I am seeing the same behavior on Docker 1.11.1.

**Comment by hoelzro** [comment] 2016-05-03 16:22
For better or for worse, I was finally just able to reproduce this myself.  Now hopefully I can actually fix it!

**Comment by washort** [comment] 2016-05-03 20:39
I discovered this after creating my own docker image that uses rlwrap. Problem gets worse: I've tried it under docker 1.8.3 and docker 1.10.3 on a Debian host (both succeed), and under docker 1.10.3 (success) and 1.11.1 (failure) on Ubuntu. So I don't think it's: an rlwrap bug, a kernel bug, or a docker version-specific bug.

**Comment by hoelzro** [comment] 2016-05-03 20:43
@washort The more I dig into this, the more I'm convinced it's a Docker bug.  `rlwrap` is just asking the kernel for its terminal size; I'm guessing that Docker isn't properly initializing the terminal size for some reason.

**Comment by washort** [comment] 2016-05-03 21:00
That's my impression. I did find that if I ran rlwrap from a bash prompt launched with `docker run`, it works. (But using `bash -c` did not.)

**Comment by hoelzro** [comment] 2016-05-06 02:34
The docker image no longer uses rlwrap, so this should be fixed now.

**Comment by bhtek** [comment] 2016-05-06 03:15
Awesome. Thanks.

**Closed as completed** 2016-05-09 13:10 UTC
